type: object
description: Address proof settings.
properties:
  weights:
    type: object
    description: |-
      Property weights that are used for the KYC document verification process.

      All KYC documents start the verification process with a score of 100.
      If a check fails, the score is reduced by the corresponding weight.
      For example, if the `firstName` check weight is set to `5`, and the check fails,
      the KYC document score becomes `95`.
    properties:
      firstName:
        type: integer
        minimum: 0
        maximum: 100
        description: Weight added if the customer's first name is not matched.
      lastName:
        type: integer
        minimum: 0
        maximum: 100
        description: Weight added if the customer's last name is not matched.
      line1:
        type: integer
        minimum: 0
        maximum: 100
        description: Weight added if the customer's address is not matched.
      city:
        type: integer
        minimum: 0
        maximum: 100
        description: Weight added if the customer's city is not matched.
      region:
        type: integer
        minimum: 0
        maximum: 100
        description: Weight added if the customer's region is not matched.
      postalCode:
        type: integer
        minimum: 0
        maximum: 100
        description: Weight added if the customer's postal code is not matched.
      date:
        type: integer
        minimum: 0
        maximum: 100
        description: Weight added if a date is not detected on the document.
      phone:
        type: integer
        minimum: 0
        maximum: 100
        description: |-
          Weight added if a phone number is not detected on the document.
      documentSubtype:
        type: integer
        minimum: 0
        maximum: 100
        description: |-
          Weight added if the document is not one of the recognized document subtypes.
          For a list of available subtypes, see [KycDocumentSubtypes](https://github.com/Rebilly/api-definitions/blob/main/openapi/components/schemas/KycDocument/KycDocumentSubtypes.yaml).
  thresholds:
    type: object
    description: Pass and fail threshold definition for the document verification process.
    properties:
      rejectBelow:
        type: integer
        minimum: 0
        maximum: 100
        description: Overall score by which an identity proof document fails the verification process.
      acceptAbove:
        type: integer
        minimum: 0
        maximum: 100
        description: Overall score by which an identity proof document passes the verification process.

