type: object
properties:
  weights:
    type: object
    description: The weights of all matched properties.
    properties:
      firstName:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of firstName.
      lastName:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of lastName.
      line1:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of line1.
      city:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of city.
      region:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of region.
      postalCode:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of postalCode.
      date:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of date.
      phone:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of phone.
      documentSubtype:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of documentSubtype.
  thresholds:
    type: object
    description: The thresholds to determine the document status.
    properties:
      rejectBelow:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of rejectBelow.
      acceptAbove:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of acceptAbove.

