type: object
properties:
  weights:
    type: object
    description: The weights of all matched properties.
    properties:
      containsImage:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of containsImage.
      isIdentityDocument:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of isIdentityDocument.
      isPublishedOnline:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of isPublishedOnline.
      firstName:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of firstName.
      lastName:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of lastName.
      expirationDate:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of `expirationDate`.
      dateOfBirth:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of dateOfBirth.
      matchesDateOfBirth:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of matchesDateOfBirth.
      issueDate:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of issueDate.
      hasMinimalAge:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of hasMinimalAge.
      hasMatchingFaceProof:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of hasMatchingFaceProof.
      nationality:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of nationality.
      documentSubtype:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of documentSubtype.
  thresholds:
    type: object
    description: The thresholds to determine the document status.
    properties:
      rejectBelow:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of rejectBelow.
      acceptAbove:
        type: integer
        minimum: 0
        maximum: 100
        description: The weight of acceptAbove.
