post:
  summary: Application instance was disabled
  operationId: application-instance-disabled
  x-products:
    - Users
  tags:
    - Application owners
  requestBody:
    $ref: ../components/requestBodies/ApplicationInstanceDisabled.yaml
  responses:
    2xx:
      description: Returns any 2xx status to indicate that the data received.
