get:
  x-products:
    - Users
  tags:
    - Email delivery settings
  summary: Retrieve email delivery settings
  operationId: GetEmailDeliverySettingCollection
  x-sdk-operation-name: getAll
  description: Retrieves email delivery settings.
  parameters:
    - $ref: ../components/parameters/collectionLimit.yaml
    - $ref: ../components/parameters/collectionOffset.yaml
    - $ref: ../components/parameters/collectionFilter.yaml
    - $ref: ../components/parameters/collectionSort.yaml
    - $ref: ../components/parameters/collectionQuery.yaml
  responses:
    '200':
      description: List of email delivery settings retrieved.
      headers:
        Pagination-Total:
          $ref: ../components/headers/Pagination-Total.yaml
        Pagination-Limit:
          $ref: ../components/headers/Pagination-Limit.yaml
        Pagination-Offset:
          $ref: ../components/headers/Pagination-Offset.yaml
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/EmailDeliverySetting.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
post:
  x-products:
    - Users
  tags:
    - Email delivery settings
  summary: Create an email delivery setting
  operationId: PostEmailDeliverySetting
  x-sdk-operation-name: create
  description: |-
    Creates an email delivery setting.
    Email delivery settings are used together with email messages,
    or templates, to send emails.
  responses:
    '201':
      description: Email delivery setting created.
      headers:
        Location:
          $ref: ../components/headers/Location.yaml
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EmailDeliverySetting.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '422':
      $ref: ../components/responses/ValidationError.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/EmailDeliverySetting.yaml
    description: Email delivery setting resource.
    required: true
