type: object
description: Financial settings.
required:
  - settlementSettings
properties:
  settlementSettings:
    $ref: ./SettlementSettings.yaml
  riskReserveSettings:
    description: |-
      Risk reserve settings.
      Use these settings to set up funds reserves before settlement.
    type: array
    items:
      type: object
      required:
        - filter
        - bips
        - period
      properties:
        filter:
          description: Filter that is based on the properties of the transaction and used to determine when to apply the settings.
          minLength: 1
          maxLength: 255
          example: 'paymentInstrument.method:payment-card'
          type: string
        bips:
          $ref: ./Bips.yaml
        period:
          description: Instruction for calculating the reserve release time.
          allOf:
            - $ref: ./SchedulingMethodDateInterval.yaml
