summary: Application instance enabled
operationId: application-instance-enabled
x-products:
  - Users
tags:
  - Application owners
requestBody:
  $ref: ../components/requestBodies/Webhooks/ApplicationInstanceEnabled.yaml
responses:
  '2xx':
    description: Returns any 2xx status to indicate that data is received.
