summary: Application instance was enabled
operationId: application-instance-enabled
x-products:
  - Full
  - Users
tags:
  - Application owners
requestBody:
  $ref: ../components/requestBodies/Webhooks/ApplicationInstanceEnabled.yaml
responses:
  '2xx':
    description: Return any 2xx status to indicate that the data was received successfully.
