summary: Application instance disabled
operationId: application-instance-disabled
x-products:
  - Users
tags:
  - Application owners
requestBody:
  $ref: ../components/requestBodies/Webhooks/ApplicationInstanceDisabled.yaml
responses:
  '2xx':
    description: Returns any 2xx status to indicate that data is received.
