type: object
description: |-
  Priority level settings for AML source matches. \
  `p0` is critical priority level, and `p3` is low priority level. \
  All source types in all hits are considered, and the one with the highest priority level is set in the resulting AML check.
properties:
  pep:
    type: object
    description: Priorities for the `pep` source type.
    properties:
      veryStrong:
        $ref: ./AmlPriority.yaml
      strong:
        $ref: ./AmlPriority.yaml
      medium:
        $ref: ./AmlPriority.yaml
      weak:
        $ref: ./AmlPriority.yaml
  enforcements:
    type: object
    description: Priorities for the `enforcement` source type.
    properties:
      veryStrong:
        $ref: ./AmlPriority.yaml
      strong:
        $ref: ./AmlPriority.yaml
      medium:
        $ref: ./AmlPriority.yaml
      weak:
        $ref: ./AmlPriority.yaml
  stateOwnedEnterprise:
    type: object
    description: Priorities for the `state-owned-enterprise` source type.
    properties:
      veryStrong:
        $ref: ./AmlPriority.yaml
      strong:
        $ref: ./AmlPriority.yaml
      medium:
        $ref: ./AmlPriority.yaml
      weak:
        $ref: ./AmlPriority.yaml
  sanctions:
    type: object
    description: Priorities for the `sanctions` source type.
    properties:
      veryStrong:
        $ref: ./AmlPriority.yaml
      strong:
        $ref: ./AmlPriority.yaml
      medium:
        $ref: ./AmlPriority.yaml
      weak:
        $ref: ./AmlPriority.yaml
  adverseMedia:
    type: object
    description: Priorities for the `adverse-media` source type.
    properties:
      veryStrong:
        $ref: ./AmlPriority.yaml
      strong:
        $ref: ./AmlPriority.yaml
      medium:
        $ref: ./AmlPriority.yaml
      weak:
        $ref: ./AmlPriority.yaml
