type: object
properties:
  defaultTaxCalculator:
    type: object
    description: The settings for tax calculation.
    required:
      - type
    properties:
      type:
        type: string
        description: The type of the tax calculator.
        enum:
          - taxjar
          - flat
      rate:
        type: number
        nullable: true
        format: float
        description: The rate for flat tax calculation.
  kyc:
    $ref: ../KycSettings.yaml
  taxLocations:
    type: array
    description: >-
      Additional organization addresses where merchant may need to collect taxes using `taxjar` tax calculator.

      Available only for US-based organizations.
    items:
      $ref: ./OrganizationSettings.yaml
