type: object
description: Organization settings.
properties:
  defaultTaxCalculator:
    type: object
    description: Tax calculation settings.
    required:
      - type
    properties:
      type:
        type: string
        description: Type of tax calculator.
        enum:
          - taxjar
          - avalara
          - flat
      rate:
        type: number
        nullable: true
        format: float
        description: Rate for flat tax calculation.
  billing:
    description: Global organization settings for billing.
    type: object
    properties:
      pendingOrderTtl:
        description: Length of time, in ISO-8601 durations format, before which a pending order is automatically abandoned.
        type: string
        example: P7D
        nullable: true
        default: null
  taxLocations:
    type: array
    description: |-
      Additional organization addresses where a merchant may want to collect taxes using the `taxjar` tax calculator.

      Available only for US-based organizations.
    items:
      $ref: ./TaxLocation.yaml
  notifications:
    description: Organization access-change notification settings.
    type: object
    properties:
      notifyOnUserAccessChanges:
        description: Whether to send notification when a user's access changes.
        type: boolean
        default: false
      notifyOnApiKeyAccessChanges:
        description: Whether to send notification when an API key's access changes.
        type: boolean
        default: false
      notificationEmailAddresses:
        description: List of email addresses to send notifications to.
        type: array
        items:
          type: string
          format: email
        default: []
