type: object
properties:
  defaultTaxCalculator:
    type: object
    description: Tax calculation settings.
    required:
      - type
    properties:
      type:
        type: string
        description: Type of tax calculator.
        enum:
          - taxjar
          - avalara
          - flat
      rate:
        type: number
        nullable: true
        format: float
        description: Rate for flat tax calculation.
  taxLocations:
    type: array
    description: |-
      Additional organization addresses where a merchant may want to
      collect taxes using the `taxjar` tax calculator.

      Available only for US-based organizations.
    items:
      $ref: ./TaxLocation.yaml
