allOf:
  - $ref: ./Application.yaml
  - properties:
      _embedded:
        type: object
        description: Embedded objects that are requested by the `expand` query parameter.
        readOnly: true
        properties:
          applicationInstance:
            $ref: ../ApplicationInstance.yaml
