allOf:
  - $ref: ./Application.yaml
  - properties:
      _embedded:
        type: array
        description: Embedded objects that are requested by the `expand` query parameter.
        readOnly: true
        minItems: 1
        items:
          anyOf:
            - $ref: ./ApplicationInstanceEmbed.yaml
