type: object
description: Website settings.
properties:
  cashierForm:
    type: object
    description: Cashier form settings.
    properties:
      theme:
        description: Various theme settings used in the cashier form.
        type: object
        properties:
          colorPrimary:
            description: Primary color for the cashier form in hexadecimal format.
            type: string
            maxLength: 6
            default: '0044d4'
          colorSecondary:
            description: Secondary color for the cashier form in hexadecimal format.
            type: string
            maxLength: 6
            default: 'ffffff'
          buttonTemplate:
            description: Submit button template. `{{amount}}` can be used as a placeholder for amount and currency.
            type: string
            maxLength: 100
            example: Pay {{amount}}
  paymentForm:
    type: object
    description: Payment form settings.
    required:
      - type
    properties:
      css:
        description: Hosted payment form [CSS options](https://www.rebilly.com/docs/content/concepts-and-features/tutorial/customize-style-rebilly-instruments/#2-use-css-property-to-override-any-styles).
        type: string
      theme:
        description: Hosted payment form [theme options](https://www.rebilly.com/docs/content/concepts-and-features/tutorial/customize-style-rebilly-instruments/#adjust-the-default-style).
        type: object
        additionalProperties:
          type: string
        example:
          colorPrimary: '#504CCA'
      features:
        description: Hosted payment form features.
        type: object
        properties:
          showCoupons:
            type: array
            nullable: true
            items:
              type: string
